version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - myspot
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    networks:
      - myspot
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - myspot
    ports:
      - 6379:6379
    # volumes: 
    #   - redis:/data

networks:
  myspot:
    name: myspot-network

volumes:
  postgres:
    driver: local
  mongo:
    driver: local
  # redis:
  #   driver: local
  